import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Card } from "@/components/ui/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          {/* <Link> = navigation côté client (pas de rechargement complet de la page) */}
          <nav className="flex gap-4 p-3 text-blue-600 underline">
            <Link href="/">Accueil</Link>
            <Link href="/serveur">Page serveur</Link>
            <Link href="/client">Page client</Link>
          </nav>
        </header>
        <div className="p-3">
          {children}
        </div>
      </body>
    </html>
  );
}
